[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build phase needed for FastAPI'"]

[start]
cmd = "cd backend && gunicorn main:app --config gunicorn_conf.py --bind 0.0.0.0:$PORT"
